apiVersion: apps/v1
kind: Deployment
metadata:
  name: mpngodb
  namespace: roboshop
  labels: # these labels are deployment labels
    app: mongodb
    project: roboshop
    tier: db
spec:
  replicas: 1
  selector:
    matchLabels: # these labels are used to find the pods
      app: mongodb
      project: roboshop
      tier: db
    template:   ###related to pod
    metadata:
      labels: # these labels are pod labels
        app: mongodb
        project: roboshop
        tier: db
    spec:
      containers:
      - name: mongodb
        image: deepthi555/mongodb:v1
        imagePullPolicy: Always
---
apiVersion: v1    ####clusterip(service -if want to communicate or expose)
kind: Service
metadata:
  name: mongodb
  namespace: roboshop
spec:
  selector:
    app: mongodb
    project: roboshop
    tier: db
  ports:
  - protocol: TCP
    port: 27017 #service-port
    targetPort: 27017 #container-port